## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: "/home/MinaRyten/Emil/projects/MANE_select_expression/"

# prefix of all output files (optional; default = "sample")
sample_name: "Temporal_lobe"

# reference genome as fasta (required)
genome: "/home/JHEmilGustavsson/MinaRyten/Emil/references/GRCh38.primary_assembly.genome.fa"

# ONT reads in fastq format
reads_fastq: "/home/MinaRyten/Emil/Human_brain_direct_cDNA/Temporal_lobe_PAG09924/Temporal_lobe_PAG09924_pass.fastq"

# Calculate various statistics with nanostat:
run_nanostat: True

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: True

# kit used (e.g. PCS109,PCS110,PCS111,LSK114). Default (PCS109)
kit: "PCS111"

# Options passed to pychopper:
pychopper_opts: ""

# Options passed to minimap2:
minimap2_opts: "-uf -k14 --MD"

# threads (default = 30)
threads: 100

# input annotation data required for sqanti (required)
# make sure the contig names in the annotation matches the input SAM file
gtf: "/home/JHEmilGustavsson/MinaRyten/Emil/references/gencode.v44.annotation.gtf"

## ------------------------------ TALON ------------------------------ ##
# Number of reads required to call a novel transcript PER dataset:
MIN_COUNT: 2