## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: "/home/MinaRyten/Emil/projects/APP_manuscript/ONT_long_read_analysis/sample_5292"

# prefix of all output files (optional; default = "sample")
sample_name: "sample_5292"

# reference genome as fasta (required):
genome: "/home/MinaRyten/Emil/references/GRCh38.primary_assembly.genome.fa"

# ONT reads in fastq format (required):
reads_fastq: "/home/MinaRyten/Emil/public_data/long-read/Ebbert_2023/sample_5292_PAG75292.fastq"

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: True

# kit used (e.g. PCS109,PCS110,PCS111,LSK114). Default (PCS109)
kit: "PCS111"

# Options passed to pychopper:
pychopper_opts: ""

# Options passed to minimap2:
minimap2_opts: "-uf -k14 --MD"

# threads (default = 30)
threads: 150

# Use exiting annotation as guide for stringtie2:
use_guide_annotation: false

# reference annotation as GTF (required if use_guide_annotation = true):
annotation: "/home/MinaRyten/Emil/references/gencode.v38.annotation.gtf"

# Options passed to stringtie2:
stringtie_opts: ""
