name: ont_stringtie
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - snakemake==7.18.2
 - python>3.6
 - nanostat==1.6
 - bioconda::pychopper=2.7.10
 - minimap2==2.28
 - samtools==1.18
 - stringtie==2.2.3