$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

properties:
  workdir:
    type: string
    minLength: 1

  sample_name:
    type: string
    default: "sample"
    minLength: 1

  genome:
    type: string
    minLength: 1

  reads_fastq:
    type: string
    default: ""

  gtf:
    type: string
    minLength: 1

  threads:
    type: integer
    default: 30


required:
  - workdir
  - genome
  - gtf
